<?php
    if(isset($_POST['submit']))
    {
        if(isset($_POST['search']))
        {
            header("location:index.php?a=29&search='.$_POST['search'].'");
        }
        else
        {
            header("location:index.php?a=404");
        }
    }
    else
    {
        header("location:index.php?a=404");
    }
?>